"""Add progress update tracking fields

Revision ID: 62af69c6fc72
Revises: 7754e8504794
Create Date: 2026-01-17 11:34:04.109104

"""
import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = '62af69c6fc72'
down_revision = '7754e8504794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_percent_complete', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('updated_by', GUID(), nullable=False))
        batch_op.alter_column('update_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_progress_updates_updated_by'), ['updated_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_updates_updated_by'))
        batch_op.alter_column('update_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('updated_by')
        batch_op.drop_column('previous_percent_complete')

    # ### end Alembic commands ###
