"""Update milestones table for OpenAPI compliance

Revision ID: 7754e8504794
Revises: 9d1ae3c65d7a
Create Date: 2026-01-15 05:53:57.026335

"""
import sqlalchemy as sa
from alembic import op

from app.models.types import GUID, JSONB

# revision identifiers, used by Alembic.
revision = '7754e8504794'
down_revision = '9d1ae3c65d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_dummies_name_company')
    )
    with op.batch_alter_table('dummies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dummies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dummies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_dummies_name'), ['name'], unique=False)

    op.create_table('projects',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=False),
    sa.Column('planned_finish_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ms_project_uid', sa.String(length=50), nullable=True),
    sa.Column('ms_project_guid', sa.String(length=50), nullable=True),
    sa.Column('ms_project_save_version', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_saved_date', sa.DateTime(), nullable=True),
    sa.Column('calendar_uid', sa.Integer(), nullable=True),
    sa.Column('minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('minutes_per_week', sa.Integer(), nullable=False),
    sa.Column('days_per_month', sa.Integer(), nullable=False),
    sa.Column('week_start_day', sa.Integer(), nullable=False),
    sa.Column('default_start_time', sa.Time(), nullable=False),
    sa.Column('default_finish_time', sa.Time(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('initialized', 'active', 'completed', 'cancelled', 'on_hold')", name='ck_projects_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_projects_company_code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('resources',
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('ms_project_uid', sa.Integer(), nullable=True),
    sa.Column('standard_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overtime_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('labor', 'material', 'cost')", name='ck_resources_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_resources_company_name')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_type'), ['type'], unique=False)

    op.create_table('evm_snapshots',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=False),
    sa.Column('planned_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('earned_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_at_completion', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimate_at_completion', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimate_to_complete', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_at_completion', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('schedule_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cost_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('schedule_performance_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_performance_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('to_complete_performance_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evm_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evm_snapshots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evm_snapshots_status_date'), ['status_date'], unique=False)

    op.create_table('expenses',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('resource_id', GUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planned_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('material', 'fixed', 'other')", name='ck_expenses_category'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_resource_id'), ['resource_id'], unique=False)

    op.create_table('milestones',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget_weight', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_achieved', sa.Boolean(), nullable=False),
    sa.Column('ms_project_uid', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actual_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('achieved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_rae', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_rae_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('upcoming', 'achieved', 'missed')", name='ck_milestones_status'),
    sa.CheckConstraint('budget_weight >= 0 AND budget_weight <= 1', name='ck_milestones_budget_weight_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ms_project_uid', name='uq_milestones_project_uid')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_achieved_date'), ['achieved_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_is_achieved'), ['is_achieved'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_target_date'), ['target_date'], unique=False)

    op.create_table('tasks',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('parent_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ms_project_uid', sa.Integer(), nullable=True),
    sa.Column('wbs_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True),
    sa.Column('planned_finish_date', sa.DateTime(), nullable=True),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_finish_date', sa.DateTime(), nullable=True),
    sa.Column('percent_complete', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('planned_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('earned_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('remaining_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed', 'cancelled')", name='ck_tasks_status'),
    sa.CheckConstraint("type IN ('task', 'summary', 'milestone')", name='ck_tasks_type'),
    sa.CheckConstraint('percent_complete >= 0 AND percent_complete <= 100', name='ck_tasks_percent_complete'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ms_project_uid', name='uq_tasks_project_uid')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_is_critical'), ['is_critical'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_planned_finish_date'), ['planned_finish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_planned_start_date'), ['planned_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_wbs_code'), ['wbs_code'], unique=False)

    op.create_table('assignments',
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('resource_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('planned_work_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_work_minutes', sa.Integer(), nullable=True),
    sa.Column('planned_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'resource_id', name='uq_assignments_task_resource')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_task_id'), ['task_id'], unique=False)

    op.create_table('milestone_tasks',
    sa.Column('milestone_id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', 'task_id', name='uq_milestone_tasks_pair')
    )
    with op.batch_alter_table('milestone_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestone_tasks_task_id'), ['task_id'], unique=False)

    op.create_table('progress_updates',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('percent_complete', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('earned_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_updates_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_updates_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_updates_update_date'), ['update_date'], unique=False)

    op.create_table('rae_entries',
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('identified_date', sa.Date(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('details', JSONB(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('technical', 'financial', 'schedule', 'resource', 'quality', 'other')", name='ck_rae_entries_category'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_rae_entries_severity'),
    sa.CheckConstraint("status IN ('open', 'mitigated', 'resolved', 'closed')", name='ck_rae_entries_status'),
    sa.CheckConstraint("type IN ('risk', 'assumption', 'exception')", name='ck_rae_entries_type'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rae_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rae_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rae_entries_identified_date'), ['identified_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rae_entries_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_rae_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rae_entries_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rae_entries_type'), ['type'], unique=False)

    op.create_table('task_predecessors',
    sa.Column('predecessor_id', GUID(), nullable=False),
    sa.Column('successor_id', GUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lag_minutes', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('FS', 'SS', 'FF', 'SF')", name='ck_task_predecessors_type'),
    sa.CheckConstraint('predecessor_id != successor_id', name='ck_task_predecessors_no_self_reference'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_task_predecessors_pair')
    )
    with op.batch_alter_table('task_predecessors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_predecessors_predecessor_id'), ['predecessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_predecessors_successor_id'), ['successor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_predecessors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_predecessors_successor_id'))
        batch_op.drop_index(batch_op.f('ix_task_predecessors_predecessor_id'))

    op.drop_table('task_predecessors')
    with op.batch_alter_table('rae_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rae_entries_type'))
        batch_op.drop_index(batch_op.f('ix_rae_entries_task_id'))
        batch_op.drop_index(batch_op.f('ix_rae_entries_status'))
        batch_op.drop_index(batch_op.f('ix_rae_entries_severity'))
        batch_op.drop_index(batch_op.f('ix_rae_entries_identified_date'))
        batch_op.drop_index(batch_op.f('ix_rae_entries_category'))

    op.drop_table('rae_entries')
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_updates_update_date'))
        batch_op.drop_index(batch_op.f('ix_progress_updates_task_id'))
        batch_op.drop_index(batch_op.f('ix_progress_updates_project_id'))

    op.drop_table('progress_updates')
    with op.batch_alter_table('milestone_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_milestone_tasks_milestone_id'))

    op.drop_table('milestone_tasks')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_task_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_resource_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_project_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_wbs_code'))
        batch_op.drop_index(batch_op.f('ix_tasks_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_planned_start_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_planned_finish_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_name'))
        batch_op.drop_index(batch_op.f('ix_tasks_is_critical'))

    op.drop_table('tasks')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_target_date'))
        batch_op.drop_index(batch_op.f('ix_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_name'))
        batch_op.drop_index(batch_op.f('ix_milestones_is_achieved'))
        batch_op.drop_index(batch_op.f('ix_milestones_achieved_date'))

    op.drop_table('milestones')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_resource_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_project_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    op.drop_table('expenses')
    with op.batch_alter_table('evm_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evm_snapshots_status_date'))
        batch_op.drop_index(batch_op.f('ix_evm_snapshots_project_id'))

    op.drop_table('evm_snapshots')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_type'))
        batch_op.drop_index(batch_op.f('ix_resources_name'))
        batch_op.drop_index(batch_op.f('ix_resources_is_active'))
        batch_op.drop_index(batch_op.f('ix_resources_company_id'))

    op.drop_table('resources')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_company_id'))

    op.drop_table('projects')
    with op.batch_alter_table('dummies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dummies_name'))
        batch_op.drop_index(batch_op.f('ix_dummies_is_active'))
        batch_op.drop_index(batch_op.f('ix_dummies_company_id'))

    op.drop_table('dummies')
    # ### end Alembic commands ###
