"""Add milestone_id to expenses for milestone allocation

Revision ID: aca11ddc49be
Revises: 7754e8504794
Create Date: 2026-01-15 21:33:41.280270

"""
import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = 'aca11ddc49be'
down_revision = '7754e8504794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_id', GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_foreign_key('fk_expenses_milestone_id', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_milestone_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_milestone_id'))
        batch_op.drop_column('milestone_id')

    # ### end Alembic commands ###
