"""Create dummies table with indexes and constraints

Revision ID: fc4baed52c98
Revises:
Create Date: 2026-01-08 20:03:41.876428

"""
import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = 'fc4baed52c98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False,
              server_default=sa.true()),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='uq_dummies_name_company')
    )
    with op.batch_alter_table('dummies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dummies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dummies_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dummies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dummies_is_active'))
        batch_op.drop_index(batch_op.f('ix_dummies_company_id'))

    op.drop_table('dummies')
    # ### end Alembic commands ###
